// config.js - Insightología Configuration
const CONFIG = {
  // Google Sheet publicado como CSV
  SHEET_CSV_URL: 'https://docs.google.com/spreadsheets/d/1iXTCqt8MevnbPK0Ng-BaV4rh1ci1rZNEV0UQoeJAiGY/export?format=csv',

  // Endpoint del backend serverless en Vercel o local
  API_ORACLE_URL: '/api/oracle',

  // Webhook de Google Apps Script para guardar preguntas en Google Sheets
  GOOGLE_SHEETS_WEBHOOK_URL: 'https://script.google.com/macros/s/AKfycbzAGTO9dy8O3H3Sd5c29D9F5Kt3QdooamOIu5R4j59skATtjIuo67B5xVtwzxUkIHI4zw/exec',

  // Timeout para respuesta de API (ms)
  TIMEOUT_MS: 5000,

  // Tiempo de visualización automática antes de ZOOM OUT (ms)
  AUTO_RESET_MS: 20000,

  // Catálogo completo enriquecido con tags de los 30 años de El Ojo de Iberoamérica (50 frases)
  // Incluye: tema, funcion, tono, flag, comodin y premio_el_ojo
  CATALOG_PHRASES: [
  {
    "id": "1",
    "frase": "Para qué mentir, si podés teletransportarte",
    "marca": "Cerveza Andes",
    "agencia": "Del Campo Nazca Saatchi & Saatchi",
    "pais": "Argentina",
    "ano": "2010",
    "tipo": "Publicidad",
    "tema": "Amor y vínculos; Identidad",
    "funcion": "Humor o absurdo",
    "tono": "Absurdo",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.adlatina.com/publicidad/del-campo-nazca-saatchi-saatchi-presenta-el-caso-andes-teletransporter"
  },
  {
    "id": "2",
    "frase": "Einstein estaba equivocado.",
    "marca": "Cerveza Andes",
    "agencia": "Del Campo Nazca Saatchi & Saatchi",
    "pais": "Argentina",
    "ano": "2010",
    "tipo": "Publicidad",
    "tema": "Futuro y tecnología",
    "funcion": "Humor o absurdo",
    "tono": "Absurdo",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.adlatina.com/publicidad/del-campo-nazca-saatchi-saatchi-presenta-el-caso-andes-teletransporter"
  },
  {
    "id": "4",
    "frase": "Cuando los hombres y las mujeres se encuentran, nace el igualismo",
    "marca": "Quilmes",
    "agencia": "Young & Rubicam",
    "pais": "Argentina",
    "ano": "2012",
    "tipo": "Publicidad",
    "tema": "Amor y vínculos",
    "funcion": "Sentencia de oráculo",
    "tono": "Irónico",
    "flag": "Revisar",
    "motivo_flag": "Remate original modificado tras críticas (ver Notas)",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.cronista.com/negocios/quilmes-obligado-a-modificar-el-spot-publicitario-igualismo/"
  },
  {
    "id": "5",
    "frase": "Tu cuerpo pide pasta",
    "marca": "Lucchetti",
    "agencia": "Madre",
    "pais": "Argentina",
    "ano": "2014 (?)",
    "tipo": "Publicidad",
    "tema": "Placer y vida cotidiana",
    "funcion": "Empuja a actuar",
    "tono": "Cálido",
    "flag": "Depende de contexto",
    "motivo_flag": "Literal: solo funciona con comida/cuerpo",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.totalmedios.com/nota/22999/tu-cuerpo-pide-pasta-de-madre-para-mama-lucchetti"
  },
  {
    "id": "6",
    "frase": "Dejá que la vida te despeine",
    "marca": "Sedal",
    "agencia": "JWT Argentina / El Hotel",
    "pais": "Argentina",
    "ano": "2005",
    "tipo": "Publicidad",
    "tema": "Identidad; Riesgo y valentía",
    "funcion": "Empuja a actuar",
    "tono": "Cálido",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": true,
    "premio_el_ojo": "",
    "link": "https://www.latinspots.com/noticia/deja-que-la-vida-te-despeine/9108"
  },
  {
    "id": "8",
    "frase": "Bienvenido a la república independiente de tu casa",
    "marca": "IKEA",
    "agencia": "*S,C,P,F...",
    "pais": "España",
    "ano": "2006",
    "tipo": "Publicidad",
    "tema": "Placer y vida cotidiana; Identidad",
    "funcion": "Tranquiliza o relativiza",
    "tono": "Cálido",
    "flag": "Depende de contexto",
    "motivo_flag": "Habla de la casa (IKEA)",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.marketingdirecto.com/especiales/premios-eficacia/campanas-mas-eficaces-publicidad-espanola"
  },
  {
    "id": "9",
    "frase": "¿Te gusta conducir?",
    "marca": "BMW",
    "agencia": "*S,C,P,F...",
    "pais": "España",
    "ano": "1999",
    "tipo": "Publicidad",
    "tema": "Identidad; Placer y vida cotidiana",
    "funcion": "Desafía o cuestiona",
    "tono": "Irónico",
    "flag": "Depende de contexto",
    "motivo_flag": "Funciona como contrapregunta; depende de BMW/manejar",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.marketingdirecto.com/especiales/premios-eficacia/campanas-mas-eficaces-publicidad-espanola"
  },
  {
    "id": "13",
    "frase": "Mi estilo se escribe con Z",
    "marca": "El Palacio de Hierro",
    "agencia": "Terán\\TBWA",
    "pais": "México",
    "ano": "2025",
    "tipo": "Publicidad",
    "tema": "Identidad",
    "funcion": "Sentencia de oráculo",
    "tono": "Provocador",
    "flag": "Depende de contexto",
    "motivo_flag": "La 'Z' pierde sentido sin el contexto de la marca",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.merca20.com/el-palacio-de-hierro-presenta-su-nueva-imagen-te-sorprendera/"
  },
  {
    "id": "14",
    "frase": "Ser grande no es cuestión de edad",
    "marca": "El Palacio de Hierro",
    "agencia": "Terán\\TBWA",
    "pais": "México",
    "ano": "2025",
    "tipo": "Publicidad",
    "tema": "Identidad; Tiempo y país",
    "funcion": "Tranquiliza o relativiza",
    "tono": "Cálido",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": true,
    "premio_el_ojo": "",
    "link": "https://www.merca20.com/el-palacio-de-hierro-presenta-su-nueva-imagen-te-sorprendera/"
  },
  {
    "id": "17",
    "frase": "Tem coisas que só a Philco faz pra você [Hay cosas que solo Philco hace por vos]",
    "marca": "Philco",
    "agencia": "F/Nazca",
    "pais": "Brasil",
    "ano": "s/d",
    "tipo": "Publicidad",
    "tema": "Amor y vínculos",
    "funcion": "Tranquiliza o relativiza",
    "tono": "Cálido",
    "flag": "Depende de contexto",
    "motivo_flag": "Portugués + marca de electrodomésticos",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.ifd.com.br/publicidade-e-propaganda/50-slogans-mais-lembrados/"
  },
  {
    "id": "19",
    "frase": "Não tem comparação [No tiene comparación]",
    "marca": "Brastemp",
    "agencia": "Talent",
    "pais": "Brasil",
    "ano": "s/d",
    "tipo": "Publicidad",
    "tema": "Identidad; Placer y vida cotidiana",
    "funcion": "Sí o no rotundo",
    "tono": "Cálido",
    "flag": "OK",
    "motivo_flag": "Portugués (traducción entre corchetes)",
    "comodin": true,
    "premio_el_ojo": "",
    "link": "https://www.ifd.com.br/publicidade-e-propaganda/50-slogans-mais-lembrados/"
  },
  {
    "id": "21",
    "frase": "no creérsela, no ser hijo de puta, escuchar a los demás",
    "marca": "El Ojo – Charla",
    "agencia": "Equipo Wieden+Kennedy Latam",
    "pais": "Regional",
    "ano": "2025",
    "tipo": "El Ojo",
    "tema": "Trabajo y creatividad; Identidad",
    "funcion": "Empuja a actuar",
    "tono": "Provocador",
    "flag": "Revisar",
    "motivo_flag": "Lenguaje fuerte ('hijo de puta')",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.ifd.com.br/publicidade-e-propaganda/50-slogans-mais-lembrados/"
  },
  {
    "id": "22",
    "frase": "…me gustaría ver más anuncios de cerveza, de bancos, de salchichas, porque ese es nuestro trabajo real",
    "marca": "El Ojo – Charla",
    "agencia": "Toni Segarra, Alegre Roca",
    "pais": "España",
    "ano": "2023",
    "tipo": "El Ojo",
    "tema": "Trabajo y creatividad",
    "funcion": "Desafía o cuestiona",
    "tono": "Provocador",
    "flag": "Depende de contexto",
    "motivo_flag": "Fragmento con '…'; habla de publicidad",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.elojodeiberoamerica.com/revivimos-los-mas-destacado-de-las-conferencias-de-el-ojo-2025/"
  },
  {
    "id": "23",
    "frase": "La publicidad no ha cambiado sino envejecido, hagámosla nuevamente sexy",
    "marca": "El Ojo – Charla",
    "agencia": "Per Pedersen, Global Creative Chairman de Grey",
    "pais": "Global",
    "ano": "2017",
    "tipo": "El Ojo",
    "tema": "Trabajo y creatividad; Tiempo y país",
    "funcion": "Desafía o cuestiona",
    "tono": "Irónico",
    "flag": "OK",
    "motivo_flag": "Habla de publicidad",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.latinspots.com/noticia/as-vivi-toni-segarra-su-ingreso-al-saln-de-honor-del-talento-latino/68216"
  },
  {
    "id": "24",
    "frase": "…caemos en la rutina y, más de una vez, pensamos en divorciarnos",
    "marca": "El Ojo – Charla",
    "agencia": "Marina Stern, Mercado McCann",
    "pais": "Argentina",
    "ano": "2021",
    "tipo": "El Ojo",
    "tema": "Amor y vínculos; Tiempo y país",
    "funcion": "Sentencia de oráculo",
    "tono": "Irónico",
    "flag": "Depende de contexto",
    "motivo_flag": "Fragmento con '…'",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.elojodeiberoamerica.com/review-ojo-2017-20-anos-pensamiento-creativo-iberoamerica/"
  },
  {
    "id": "26",
    "frase": "la empatía es el mejor GPS",
    "marca": "El Ojo – Entrevista",
    "agencia": "Omar Carrión, Kellanova Latin America",
    "pais": "s/d",
    "ano": "2025 (?)",
    "tipo": "El Ojo",
    "tema": "Amor y vínculos; Trabajo y creatividad",
    "funcion": "Sentencia de oráculo",
    "tono": "Cálido",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": true,
    "premio_el_ojo": "",
    "link": "https://www.latinspots.com/noticia/el-ojo-de-iberoamrica-2021-cultura-emociones-e-inclusin/61138"
  },
  {
    "id": "27",
    "frase": "Yo creo que sacamos petróleo debajo de una piedra.",
    "marca": "El Ojo – Entrevista",
    "agencia": "Antonio Montero López, Contrapunto",
    "pais": "España",
    "ano": "2004",
    "tipo": "El Ojo",
    "tema": "Trabajo y creatividad",
    "funcion": "Sí o no rotundo",
    "tono": "Irónico",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.latinspots.com/noticia/latinspots185-creatividad-para-un-mundo-incierto/91670"
  },
  {
    "id": "28",
    "frase": "Las personas son más inteligentes de lo que las marcas piensan",
    "marca": "El Ojo – Charla",
    "agencia": "Lucía \"Pistola\" Mendoza, Twitter México & Latam",
    "pais": "México",
    "ano": "2021",
    "tipo": "El Ojo",
    "tema": "Trabajo y creatividad; Identidad",
    "funcion": "Desafía o cuestiona",
    "tono": "Provocador",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.latinspots.com/noticia/popai-argentina-invita-a-participar-del-taller-shopper-marketing/6491?section=negocios"
  },
  {
    "id": "29",
    "frase": "Original es una trampa. Lo fresco es libertad",
    "marca": "El Ojo – Charla",
    "agencia": "Sergio Gordilho, Africa Creative",
    "pais": "Brasil",
    "ano": "2025",
    "tipo": "El Ojo",
    "tema": "Trabajo y creatividad; Identidad",
    "funcion": "Desafía o cuestiona",
    "tono": "Provocador",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.latinspots.com/noticia/el-ojo-de-iberoamrica-2021-cultura-emociones-e-inclusin/61138"
  },
  {
    "id": "30",
    "frase": "El AI concluye. La creatividad humana desordena, es curiosa, explora.",
    "marca": "El Ojo – Charla",
    "agencia": "Damasia Merbilháa, TBWA\\Worldwide",
    "pais": "Argentina",
    "ano": "2025",
    "tipo": "El Ojo",
    "tema": "Futuro y tecnología",
    "funcion": "Sentencia de oráculo",
    "tono": "Profético",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.elojodeiberoamerica.com/revivimos-los-mas-destacado-de-las-conferencias-de-el-ojo-2025/"
  },
  {
    "id": "31",
    "frase": "La única forma de innovar, es no pretenderlo.",
    "marca": "El Ojo – Charla",
    "agencia": "Álex de la Iglesia, director y guionista",
    "pais": "España",
    "ano": "2018",
    "tipo": "El Ojo",
    "tema": "Futuro y tecnología; Trabajo y creatividad",
    "funcion": "Sentencia de oráculo",
    "tono": "Profético",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.elojodeiberoamerica.com/revivimos-los-mas-destacado-de-las-conferencias-de-el-ojo-2025/"
  },
  {
    "id": "32",
    "frase": "la valentía es contagiosa",
    "marca": "El Ojo – Charla",
    "agencia": "Equipo LePub Mexico City + Tecate",
    "pais": "México",
    "ano": "2025",
    "tipo": "El Ojo",
    "tema": "Riesgo y valentía",
    "funcion": "Empuja a actuar",
    "tono": "Cálido",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": true,
    "premio_el_ojo": "",
    "link": "https://www.infobae.com/espacio-no-editorial/2018/11/06/la-celebracion-de-la-creatividad-regional-todos-los-ganadores-de-el-ojo-de-iberoamerica/"
  },
  {
    "id": "34",
    "frase": "el algoritmo es nuestro caballo de Troya para hacer una revolución",
    "marca": "El Ojo – Charla",
    "agencia": "Alejandro Di Trolio, Cheil Worldwide",
    "pais": "España (?)",
    "ano": "2025",
    "tipo": "El Ojo",
    "tema": "Futuro y tecnología; Riesgo y valentía",
    "funcion": "Empuja a actuar",
    "tono": "Provocador",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.elojodeiberoamerica.com/revivimos-los-mas-destacado-de-las-conferencias-de-el-ojo-2025/"
  },
  {
    "id": "35",
    "frase": "la idea siempre está primero",
    "marca": "El Ojo – Charla",
    "agencia": "Rafa Quijano y Daro González, VML Argentina",
    "pais": "Argentina",
    "ano": "2025",
    "tipo": "El Ojo",
    "tema": "Trabajo y creatividad",
    "funcion": "Sentencia de oráculo",
    "tono": "Profético",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.elojodeiberoamerica.com/revivimos-los-mas-destacado-de-las-conferencias-de-el-ojo-2025/"
  },
  {
    "id": "37",
    "frase": "ser creativo hoy no es solo hacer cosas lindas, es tomar posición",
    "marca": "El Ojo – Charla",
    "agencia": "Kike Renta, DDB Latina Puerto Rico",
    "pais": "Puerto Rico",
    "ano": "2025",
    "tipo": "El Ojo",
    "tema": "Trabajo y creatividad; Identidad",
    "funcion": "Empuja a actuar",
    "tono": "Provocador",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.elojodeiberoamerica.com/revivimos-los-mas-destacado-de-las-conferencias-de-el-ojo-2025/"
  },
  {
    "id": "39",
    "frase": "La creatividad es el antídoto",
    "marca": "El Ojo – Entrevista",
    "agencia": "Tomás Ostiglia, LOLA MullenLowe",
    "pais": "España",
    "ano": "2025",
    "tipo": "El Ojo",
    "tema": "Futuro y tecnología; Trabajo y creatividad",
    "funcion": "Tranquiliza o relativiza",
    "tono": "Profético",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": true,
    "premio_el_ojo": "",
    "link": "https://www.latinspots.com/noticia/el-ojo-de-iberoamrica-2025-ia-creatividad-humana-y-nuevas-fronteras/95096"
  },
  {
    "id": "40",
    "frase": "Lo más importante de las ideas es hacerlas",
    "marca": "El Ojo – Entrevista",
    "agencia": "Tomás Ostiglia, LOLA MullenLowe",
    "pais": "España",
    "ano": "2018",
    "tipo": "El Ojo",
    "tema": "Trabajo y creatividad; Riesgo y valentía",
    "funcion": "Empuja a actuar",
    "tono": "Directo",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": true,
    "premio_el_ojo": "",
    "link": "https://www.latinspots.com/noticia/latinspots185-creatividad-para-un-mundo-incierto/91670"
  },
  {
    "id": "41",
    "frase": "Cuando tienes data, puedes vender creatividad más arriesgada con menos riesgo",
    "marca": "El Ojo – Charla",
    "agencia": "Ciro Sarmiento, Dieste",
    "pais": "EE.UU.",
    "ano": "2017",
    "tipo": "El Ojo",
    "tema": "Futuro y tecnología; Riesgo y valentía; Trabajo y creatividad",
    "funcion": "Sentencia de oráculo",
    "tono": "Directo",
    "flag": "Depende de contexto",
    "motivo_flag": "Jerga de data/ventas",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.latinspots.com/sp/noticia/ranking-las-ideas-ms-premiadas-de-el-ojo-2018/49257"
  },
  {
    "id": "44",
    "frase": "el talento camina en todas direcciones",
    "marca": "El Ojo – Entrevista",
    "agencia": "Antonio Montero López, Contrapunto",
    "pais": "España",
    "ano": "2004",
    "tipo": "El Ojo",
    "tema": "Trabajo y creatividad; Identidad",
    "funcion": "Tranquiliza o relativiza",
    "tono": "Cálido",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.elojodeiberoamerica.com/review-ojo-2017-20-anos-pensamiento-creativo-iberoamerica/"
  },
  {
    "id": "45",
    "frase": "las ideas deben ser más grandes que avisos",
    "marca": "El Ojo – Entrevista",
    "agencia": "Pablo del Campo",
    "pais": "Argentina",
    "ano": "2024",
    "tipo": "El Ojo",
    "tema": "Trabajo y creatividad; Riesgo y valentía",
    "funcion": "Empuja a actuar",
    "tono": "Provocador",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.latinspots.com/noticia/popai-argentina-invita-a-participar-del-taller-shopper-marketing/6491?section=negocios"
  },
  {
    "id": "48",
    "frase": "Es la primera idea con la que realmente sentimos que había peligro a la hora de hacerla…",
    "marca": "El Ojo – Entrevista",
    "agencia": "Pancho Cassis, LOLA MullenLowe",
    "pais": "España",
    "ano": "2018",
    "tipo": "El Ojo",
    "tema": "Riesgo y valentía",
    "funcion": "Sentencia de oráculo",
    "tono": "Profético",
    "flag": "Depende de contexto",
    "motivo_flag": "Fragmento con '…'",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.elojodeiberoamerica.com/pablo-del-campo-ingresa-en-el-salon-de-honor-del-talento-latino/"
  },
  {
    "id": "53",
    "frase": "Tenemos que vernos más",
    "marca": "Ruavieja",
    "agencia": "Leo Burnett España",
    "pais": "España",
    "ano": "2017",
    "tipo": "Publicidad",
    "tema": "Amor y vínculos",
    "funcion": "Empuja a actuar",
    "tono": "Cálido",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.marketingdirecto.com/imprescindibles/historia-marcas/historia-campofrio-anuncios-navidad"
  },
  {
    "id": "55",
    "frase": "Tomou? [¿Tomaste?]",
    "marca": "Parmalat",
    "agencia": "DM9",
    "pais": "Brasil",
    "ano": "1996",
    "tipo": "Publicidad",
    "tema": "Placer y vida cotidiana",
    "funcion": "Desafía o cuestiona",
    "tono": "Absurdo",
    "flag": "Depende de contexto",
    "motivo_flag": "Portugués + leche; solo funciona con comida/bebida",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.latinspots.com/noticia/leo-burnett-espaa-propone-volver-a-las-amistades-autnticas-con-licores-ruavieja/45730"
  },
  {
    "id": "57",
    "frase": "En navidad todo es posible.",
    "marca": "Ministerio de Defensa de Colombia",
    "agencia": "Lowe-SSP3",
    "pais": "Colombia",
    "ano": "2010",
    "tipo": "Publicidad",
    "tema": "Futuro y tecnología; Tiempo y país",
    "funcion": "Sí o no rotundo",
    "tono": "Cálido",
    "flag": "Depende de contexto",
    "motivo_flag": "Estacional (Navidad)",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://exame.com/marketing/parmalat-e-os-mamiferos-que-marcaram-o-brasil/"
  },
  {
    "id": "60",
    "frase": "¿Es muy tonto lo que estoy diciendo?",
    "marca": "VTR",
    "agencia": "Porta",
    "pais": "Chile",
    "ano": "2012",
    "tipo": "Publicidad",
    "tema": "Amor y vínculos; Identidad",
    "funcion": "Desafía o cuestiona",
    "tono": "Irónico",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.semana.com/pais/articulo/colombia-mercadeo-navidad-para-ganar-guerra/141091/"
  },
  {
    "id": "63",
    "frase": "Huevo estrellado",
    "marca": "Bachoco",
    "agencia": "Terán\\TBWA",
    "pais": "México",
    "ano": "",
    "tipo": "Publicidad",
    "tema": "Placer y vida cotidiana",
    "funcion": "Humor o absurdo",
    "tono": "Absurdo",
    "flag": "Depende de contexto",
    "motivo_flag": "Literal: nombre de producto",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.produ.com/mercadeo/noticias/leo-burnett-mexico-y-corona-senalan-que-america-siempre-ha-sido-grande-en-un-nuevo-spot/"
  },
  {
    "id": "66",
    "frase": "Canelón de Pollo",
    "marca": "Bachoco",
    "agencia": "Terán\\TBWA (?)",
    "pais": "México",
    "ano": "",
    "tipo": "Publicidad",
    "tema": "Placer y vida cotidiana",
    "funcion": "Humor o absurdo",
    "tono": "Absurdo",
    "flag": "Depende de contexto",
    "motivo_flag": "Literal: nombre de producto",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.elfinanciero.com.mx/food-and-drink/2025/09/21/hoy-toca-pollo-quien-es-dueno-de-bachoco-marca-que-innovo-con-la-venta-de-huevos-por-docena/"
  },
  {
    "id": "68",
    "frase": "Todos somos expertos",
    "marca": "Banca de Quinielas del Uruguay",
    "agencia": "Publicis Ímpetu",
    "pais": "Uruguay",
    "ano": "2019",
    "tipo": "Publicidad",
    "tema": "Identidad; Trabajo y creatividad",
    "funcion": "Tranquiliza o relativiza",
    "tono": "Cálido",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": true,
    "premio_el_ojo": "",
    "link": "https://naranti.com/noticias/anuncios-espectaculares-bachoco"
  },
  {
    "id": "69",
    "frase": "Seguí moviéndote",
    "marca": "Ford",
    "agencia": "JWT Argentina",
    "pais": "Argentina",
    "ano": "",
    "tipo": "Publicidad",
    "tema": "Riesgo y valentía; Futuro y tecnología",
    "funcion": "Empuja a actuar",
    "tono": "Directo",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": true,
    "premio_el_ojo": "",
    "link": "https://www.adlatina.com/publicidad/publicis-%C3%ADmpetu-y-banca-de-quinielas-de-uruguay-se-consagraron-con-el-gran-effie"
  },
  {
    "id": "70",
    "frase": "Para abrir caminos se necesita maquinaria pesada",
    "marca": "Holcim Ecuador",
    "agencia": "Maruri Grey",
    "pais": "Ecuador",
    "ano": "2023",
    "tipo": "Publicidad",
    "tema": "Riesgo y valentía; Trabajo y creatividad",
    "funcion": "Sentencia de oráculo",
    "tono": "Directo",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.lanacion.com.ar/economia/la-publicidad-debe-ser-amigable-y-respetuosa-del-consumidor-nid1423265/"
  },
  {
    "id": "72",
    "frase": "Naturalmente impredecible",
    "marca": "Del Sur",
    "agencia": "Paradais DDB",
    "pais": "Ecuador",
    "ano": "2023",
    "tipo": "Publicidad",
    "tema": "Futuro y tecnología; Identidad",
    "funcion": "Sentencia de oráculo",
    "tono": "Profético",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": true,
    "premio_el_ojo": "",
    "link": "https://www.eluniverso.com/larevista/sociedad/effie-awards-ecuador-cumplio-dos-decadas-de-premiar-a-las-ideas-que-funcionan-nota/"
  },
  {
    "id": "74",
    "frase": "Eran otros tiempos",
    "marca": "Quilmes",
    "agencia": "Young & Rubicam",
    "pais": "Argentina",
    "ano": "2002",
    "tipo": "Publicidad",
    "tema": "Tiempo y país",
    "funcion": "Tranquiliza o relativiza",
    "tono": "Irónico",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.adlatina.com/publicidad/%E2%80%9Chimno%E2%80%9D-un-homenaje-al-f%C3%BAtbol"
  },
  {
    "id": "75",
    "frase": "Lo importante es el chip",
    "marca": "CTI",
    "agencia": "",
    "pais": "Argentina",
    "ano": "2004",
    "tipo": "Publicidad",
    "tema": "Futuro y tecnología",
    "funcion": "Sentencia de oráculo",
    "tono": "Directo",
    "flag": "Depende de contexto",
    "motivo_flag": "Habla de un chip/celular (CTI)",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.youtube.com/watch?v=VWkkWe8U_n8"
  },
  {
    "id": "76",
    "frase": "Uno de cada 10 hombres es gay",
    "marca": "Fernet Cinzano",
    "agencia": "",
    "pais": "Argentina",
    "ano": "2004",
    "tipo": "Publicidad",
    "tema": "Identidad; Amor y vínculos",
    "funcion": "Humor o absurdo",
    "tono": "Provocador",
    "flag": "Revisar",
    "motivo_flag": "Tema sensible; evaluar si va en un oráculo público",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.youtube.com/watch?v=Sz48pFGybzc"
  },
  {
    "id": "77",
    "frase": "Hacele caso a tu sed",
    "marca": "Sprite",
    "agencia": "",
    "pais": "Argentina",
    "ano": "1998",
    "tipo": "Publicidad",
    "tema": "Placer y vida cotidiana; Identidad",
    "funcion": "Empuja a actuar",
    "tono": "Cálido",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.youtube.com/watch?v=iFQFw6vAxtA"
  },
  {
    "id": "78",
    "frase": "Si no es para vos, no es para vos",
    "marca": "BAFICI",
    "agencia": "La Comunidad",
    "pais": "Argentina",
    "ano": "",
    "tipo": "Publicidad",
    "tema": "Identidad; Amor y vínculos",
    "funcion": "Tranquiliza o relativiza",
    "tono": "Directo",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": true,
    "premio_el_ojo": "",
    "link": "https://www.adlatina.com/publicidad/preestreno-de-la-comunidad-para-el-bafici"
  },
  {
    "id": "79",
    "frase": "No es para ti",
    "marca": "Ford F-150",
    "agencia": "JWT San Juan",
    "pais": "Puerto Rico",
    "ano": "2009",
    "tipo": "Publicidad",
    "tema": "Identidad; Riesgo y valentía",
    "funcion": "Sí o no rotundo",
    "tono": "Provocador",
    "flag": "OK",
    "motivo_flag": "Nombre de la pieza premiada; confirmar que funciona como frase al aire",
    "comodin": true,
    "premio_el_ojo": "Plata – El Ojo Innovador, Radio",
    "link": "https://www.adlatina.com/articulo.php?slug=%2Fpublicidad%2Ftodos-los-ganadores-del-ojo-de-iberoam%C3%A9rica"
  },
  {
    "id": "82",
    "frase": "Devolvele la guita al taxista",
    "marca": "Publicis Graffiti (institucional)",
    "agencia": "Publicis Graffiti Argentina",
    "pais": "Argentina",
    "ano": "2009",
    "tipo": "Publicidad",
    "tema": "Identidad; Riesgo y valentía",
    "funcion": "Empuja a actuar",
    "tono": "Irónico",
    "flag": "OK",
    "motivo_flag": "Nombre de la pieza premiada; confirmar que funciona como frase al aire; argentinismo (guita)",
    "comodin": true,
    "premio_el_ojo": "Bronce – El Ojo Promo, Activación",
    "link": "https://www.adlatina.com/articulo.php?slug=%2Fpublicidad%2Ftodos-los-ganadores-del-ojo-de-iberoam%C3%A9rica"
  },
  {
    "id": "83",
    "frase": "Que vuelvan los lentos",
    "marca": "Doritos",
    "agencia": "BBDO Argentina",
    "pais": "Argentina",
    "ano": "2009",
    "tipo": "Publicidad",
    "tema": "Amor y vínculos; Tiempo y país",
    "funcion": "Sentencia de oráculo",
    "tono": "Irónico",
    "flag": "OK",
    "motivo_flag": "Nombre de la pieza premiada; confirmar que funciona como frase al aire",
    "comodin": false,
    "premio_el_ojo": "Oro – El Ojo Campañas Integradas (Productos)",
    "link": "https://www.adlatina.com/articulo.php?slug=%2Fpublicidad%2Ftodos-los-ganadores-del-ojo-de-iberoam%C3%A9rica"
  },
  {
    "id": "86",
    "frase": "Con poco me lo monto",
    "marca": "Fanta",
    "agencia": "McCann Erickson España",
    "pais": "España",
    "ano": "2009",
    "tipo": "Publicidad",
    "tema": "Trabajo y creatividad; Placer y vida cotidiana",
    "funcion": "Tranquiliza o relativiza",
    "tono": "Irónico",
    "flag": "OK",
    "motivo_flag": "Nombre de la pieza premiada; confirmar que funciona como frase al aire; expresión española",
    "comodin": false,
    "premio_el_ojo": "Bronce – El Ojo Promo (Promociones integradas)",
    "link": "https://www.adlatina.com/articulo.php?slug=%2Fpublicidad%2Ftodos-los-ganadores-del-ojo-de-iberoam%C3%A9rica"
  }
]
};

// Alias de compatibilidad
CONFIG.TEST_PHRASES = CONFIG.CATALOG_PHRASES;

// Compatible con Node / ES Modules / Browser
if (typeof module !== 'undefined' && module.exports) {
  module.exports = CONFIG;
}
