// config.js - Insightología Configuration
const CONFIG = {
  // Google Sheet publicado como CSV
  SHEET_CSV_URL: 'https://docs.google.com/spreadsheets/d/1iXTCqt8MevnbPK0Ng-BaV4rh1ci1rZNEV0UQoeJAiGY/export?format=csv',

  // Endpoint del backend serverless en Vercel o local
  API_ORACLE_URL: (typeof window !== 'undefined' && (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1'))
    ? '/api/oracle'
    : 'https://insightologia.vercel.app/api/oracle',

  // Webhook de Google Apps Script para guardar preguntas en Google Sheets
  GOOGLE_SHEETS_WEBHOOK_URL: 'https://script.google.com/macros/s/AKfycbzAGTO9dy8O3H3Sd5c29D9F5Kt3QdooamOIu5R4j59skATtjIuo67B5xVtwzxUkIHI4zw/exec',

  // Timeout para respuesta de API (ms)
  TIMEOUT_MS: 5000,

  // Tiempo de visualización automática antes de ZOOM OUT (ms)
  AUTO_RESET_MS: 20000,

  // Galería de Adivinadores / Insightólogos alternativos (rotación aleatoria por refresh)
  AVATARS: [
    {
      id: 'perez',
      name: 'Pérez',
      src: 'assets/escena-perez.webp',
      srcMobile: 'assets/escena-mobile-sin-pupila.webp',
      hands: 'assets/manos-perez.webp',
      handsMobile: 'assets/manos-mobile.png',
      eye: {
        eyeX: '48.9%',
        eyeY: '20.8%',
        pupilX: '49.596%',
        pupilY: '20.370%',
        pupilW: '1.641%',
        pupilH: '2.407%'
      }
    },
    {
      id: 'delrio',
      name: 'Del Río',
      src: 'assets/escena-delrio.webp',
      srcMobile: 'assets/escena-delrio.webp',
      hands: 'assets/manos-delrio.webp',
      eye: {
        eyeX: '48.9%',
        eyeY: '20.8%',
        pupilX: '49.511%',
        pupilY: '20.483%',
        pupilW: '1.641%',
        pupilH: '2.407%'
      }
    },
    {
      id: 'mercado',
      name: 'Mercado',
      src: 'assets/escena-mercado.webp',
      srcMobile: 'assets/escena-mercado.webp',
      hands: 'assets/manos-mercado.webp',
      eye: {
        eyeX: '48.9%',
        eyeY: '20.8%',
        pupilX: '49.652%',
        pupilY: '20.359%',
        pupilW: '1.641%',
        pupilH: '2.407%'
      }
    },
    {
      id: 'olivetto',
      name: 'Olivetto',
      src: 'assets/escena-olivetto.webp',
      srcMobile: 'assets/escena-olivetto.webp',
      hands: 'assets/manos-olivetto.webp',
      eye: {
        eyeX: '48.9%',
        eyeY: '20.8%',
        pupilX: '49.427%',
        pupilY: '20.394%',
        pupilW: '1.641%',
        pupilH: '2.407%'
      }
    },
    {
      id: 'serpa',
      name: 'Serpa',
      src: 'assets/escena-serpa.webp',
      srcMobile: 'assets/escena-serpa.webp',
      hands: 'assets/manos-serpa.webp',
      eye: {
        eyeX: '48.9%',
        eyeY: '20.8%',
        pupilX: '49.595%',
        pupilY: '20.639%',
        pupilW: '1.641%',
        pupilH: '2.407%'
      }
    },
    {
      id: 'polar',
      name: 'Polar',
      src: 'assets/escena-polar.webp',
      srcMobile: 'assets/escena-polar.webp',
      hands: 'assets/manos-polar.webp',
      eye: {
        eyeX: '48.9%',
        eyeY: '20.8%',
        pupilX: '49.603%',
        pupilY: '20.697%',
        pupilW: '1.641%',
        pupilH: '2.407%'
      }
    },
    {
      id: 'guichard',
      name: 'Guichard',
      src: 'assets/escena-guichard.webp',
      srcMobile: 'assets/escena-guichard.webp',
      hands: 'assets/manos-guichard.webp',
      eye: {
        eyeX: '48.9%',
        eyeY: '20.8%',
        pupilX: '49.602%',
        pupilY: '20.259%',
        pupilW: '1.641%',
        pupilH: '2.407%'
      }
    },
    {
      id: 'olabuenaga',
      name: 'Olabuenaga',
      src: 'assets/escena-olabuenaga.webp',
      srcMobile: 'assets/escena-olabuenaga.webp',
      hands: 'assets/manos-olabuenaga.webp',
      eye: {
        eyeX: '48.9%',
        eyeY: '20.8%',
        pupilX: '49.569%',
        pupilY: '20.721%',
        pupilW: '1.641%',
        pupilH: '2.407%'
      }
    },
    {
      id: 'visco',
      name: 'Visco',
      src: 'assets/escena-visco.webp?v=20261006-01',
      srcMobile: 'assets/escena-visco.webp?v=20261006-01',
      hands: 'assets/manos-visco.webp',
      eye: {
        eyeX: '48.9%',
        eyeY: '22.8%',
        pupilX: '49.688%',
        pupilY: '22.824%',
        pupilW: '1.641%',
        pupilH: '2.407%'
      }
    }
  ],

  // Biografías oficiales de los Insightólogos / Expertos
  EXPERT_BIOS: [
    {
      id: "mercado",
      nombre: "Martín Mercado",
      pais: "Argentina",
      bio: "Creativo argentino nacido en 1969. Pasó por TBWA (donde trabajó junto a Ernesto Savaglio), McCann Erickson y Young & Rubicam, y en 2014 fundó Mercado McCann. Es el autor de 'Para todos' de Coca-Cola, traducido a más de 20 idiomas, y de campañas recordadas para Quilmes, TyC Sports y Banco Galicia ('Marcos y Claudia'). En 2017 Adweek lo eligió entre los 10 líderes creativos del mundo, siendo el único latinoamericano de la lista; ese mismo año recibió el Diploma al Mérito Konex, TED lo había destacado en 2012 como líder para inspirar al mundo y Mercado McCann fue elegida Mejor Agencia Argentina en El Ojo de Iberoamérica. En 2025 la Academia Argentina de la Publicidad lo nombró Académico de Honor."
    },
    {
      id: "olivetto",
      nombre: "Washington Olivetto (1951-2024)",
      pais: "Brasil",
      bio: "Nacido en São Paulo, ganó su primer León en Cannes con apenas veinte años y en DPZ escribió el film del primer León de Oro de la publicidad brasileña. En 1986 cofundó W/Brasil, agencia que acumuló casi mil premios y hasta inspiró una canción de Jorge Ben Jor. Creó íconos como el 'garoto Bombril' y 'O Primeiro Sutiã' de Valisère, y fue vicepresidente del Corinthians durante la Democracia Corinthiana. Ganó más de 50 Leones en Cannes, fue el único latinoamericano en obtener el Grand Prix del Clio (2001, 'A Semana'), el único no anglosajón en el Hall of Fame del One Club y fue elegido dos veces publicitario del siglo por la asociación latinoamericana de agencias. Murió en octubre de 2024."
    },
    {
      id: "serpa",
      nombre: "Marcello Serpa",
      pais: "Brasil",
      bio: "Director de arte nacido en São Paulo que se formó en artes visuales en Alemania, donde trabajó en GGK. De vuelta en Brasil pasó por DPZ y DM9, y en 1993 se convirtió en socio y director de creación de AlmapBBDO, que lideró durante 22 años y desde donde transformó Havaianas en un símbolo de brasilidad. Creó el primer Grand Prix de Latinoamérica en Cannes (Guaraná Antarctica Diet, 1993) y bajo su mando la agencia fue tres veces Agencia del Año en el festival. Suma más de 160 Leones, fue el primer brasileño y el más joven en presidir un jurado de Cannes (2000), el primer no anglosajón en recibir el Clio Lifetime Achievement (2008) y el único brasileño distinguido con el León de San Marcos (2016)."
    },
    {
      id: "polar",
      nombre: "Humberto Polar",
      pais: "Perú",
      bio: "Uno de los directores creativos más premiados de Latinoamérica y de los pocos que ganaron Leones de Cannes en tres países distintos. Lideró la creatividad de Mayo Draftfcb Perú, donde nació el panel publicitario que genera agua potable a partir de la humedad del aire (cinco Leones en Cannes 2013), y luego fue director creativo de Grey México. Suma más de diez Leones, fue dos veces jurado de Cannes y jurado en One Show, Clio y El Sol. En paralelo es artista visual y músico electrónico, con exposiciones en América y Europa."
    },
    {
      id: "guichard",
      nombre: "Michelle Guichard",
      pais: "Chile",
      bio: "Creativa chilena que pasó por Porta, Leo Burnett y BBDO antes de convertirse en directora general creativa de Ogilvy Colombia. Es una de las fundadoras del Círculo de Creativas de Chile, espacio que impulsa a las mujeres en la creatividad publicitaria, y ganó diversos premios nacionales e internacionales. Es una voz frecuente en charlas y formación de nuevas generaciones de publicistas."
    },
    {
      id: "olabuenaga",
      nombre: "Ana María Olabuenaga",
      pais: "México",
      bio: "Empezó en 1986 como redactora y pasó por Bozell, Leo Burnett, BBDO y Terán TBWA, donde lideró la mítica campaña de El Palacio de Hierro. Rescató la agencia Noble-D'Arcy y en 2003 fundó Olabuenaga Chemistri junto a Publicis. Es la autora de 'El mensaje está en la botella'. Tiene más de 400 premios, fue la primera mujer en el Salón de la Fama del FIAP (2010), presidió jurados del FIAP y del Círculo Creativo, fue jurado en Cannes y El Sol, y en 2023 El Ojo de Iberoamérica la sumó a su Salón de la Fama junto a Toni Segarra. Carlos Monsiváis la bautizó 'la emperatriz del impacto efímero'. Es autora del libro 'Linchamientos digitales'."
    },
    {
      id: "visco",
      nombre: "Laura Visco",
      pais: "Argentina",
      bio: "Nacida en Buenos Aires, empezó en publicidad a los 19 años y pasó por Publicis Argentina, Ponce Buenos Aires (Axe, Stella Artois), Fallon London y Madre, donde hizo '44 cuadras y una baguette' para Banco Hipotecario, premiada en Cannes, D&AD y El Ojo. Como directora creativa ejecutiva de 72andSunny Amsterdam lideró 'Find Your Magic' de Axe y trabajos para Uber y Coca-Cola, y luego fue Chief Creative Officer de cuentas globales de Grey en Londres. En 2018 integró el Creative 100 de Adweek, fue destacada por AdAge como directora creativa del año y presidió un jurado de El Ojo de Iberoamérica; en 2019 recibió el premio Three Cheers de 3% por su trabajo por la diversidad en la industria."
    },
    {
      id: "delrio",
      nombre: "Anita Ríos",
      pais: "Argentina",
      bio: "Empezó a los 18 años en el área de marketing de Young & Rubicam y tardó unos dos años en pasar a creatividad. Después de Y&R y Del Campo Nazca Saatchi & Saatchi, se sumó en 2003 a VegaOlmosPonce y en 2009 se convirtió en la primera directora general creativa de la Argentina, a cargo de marcas globales como Axe, Rexona e Impulse manejadas desde Buenos Aires. Formó parte del equipo fundador de David y luego fue directora general creativa de J. Walter Thompson Buenos Aires junto a Sebastián Castañeda. En 2019 fundó Anita & Vega con Fernando Vega Olmos, donde es CCO. Suma 30 Leones de Cannes, ganó premios en El Ojo de Iberoamérica y fue jurado en ambos festivales."
    }
  ],

  // Catálogo completo enriquecido con tags de los 30 años de El Ojo de Iberoamérica (50 frases)
  // Incluye: tema, funcion, tono, flag, comodin y premio_el_ojo
  CATALOG_PHRASES: [
  {
    "id": "1",
    "frase": "Para qué mentir, si podés teletransportarte",
    "marca": "Cerveza Andes",
    "agencia": "Del Campo Nazca Saatchi & Saatchi",
    "pais": "Argentina",
    "ano": "2010",
    "tipo": "Publicidad",
    "tema": "Amor y vínculos; Identidad",
    "funcion": "Humor o absurdo",
    "tono": "Absurdo",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.adlatina.com/publicidad/del-campo-nazca-saatchi-saatchi-presenta-el-caso-andes-teletransporter",
    "frase_es": "Para qué mentir, si podés teletransportarte",
    "frase_pt": "Pra que mentir, se você pode se teletransportar",
    "pais_pt": "Argentina"
  },
  {
    "id": "2",
    "frase": "Einstein estaba equivocado.",
    "marca": "Cerveza Andes",
    "agencia": "Del Campo Nazca Saatchi & Saatchi",
    "pais": "Argentina",
    "ano": "2010",
    "tipo": "Publicidad",
    "tema": "Futuro y tecnología",
    "funcion": "Humor o absurdo",
    "tono": "Absurdo",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.adlatina.com/publicidad/del-campo-nazca-saatchi-saatchi-presenta-el-caso-andes-teletransporter",
    "frase_es": "Einstein estaba equivocado.",
    "frase_pt": "Einstein estava errado.",
    "pais_pt": "Argentina"
  },
  {
    "id": "4",
    "frase": "Cuando los hombres y las mujeres se encuentran, nace el igualismo",
    "marca": "Quilmes",
    "agencia": "Young & Rubicam",
    "pais": "Argentina",
    "ano": "2012",
    "tipo": "Publicidad",
    "tema": "Amor y vínculos",
    "funcion": "Sentencia de oráculo",
    "tono": "Irónico",
    "flag": "Revisar",
    "motivo_flag": "Remate original modificado tras críticas (ver Notas)",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.cronista.com/negocios/quilmes-obligado-a-modificar-el-spot-publicitario-igualismo/",
    "frase_es": "Cuando los hombres y las mujeres se encuentran, nace el igualismo",
    "frase_pt": "Quando os homens e as mulheres se encontram, nasce o igualismo",
    "pais_pt": "Argentina"
  },
  {
    "id": "5",
    "frase": "Tu cuerpo pide pasta",
    "marca": "Lucchetti",
    "agencia": "Madre",
    "pais": "Argentina",
    "ano": "2014 (?)",
    "tipo": "Publicidad",
    "tema": "Placer y vida cotidiana",
    "funcion": "Empuja a actuar",
    "tono": "Cálido",
    "flag": "Depende de contexto",
    "motivo_flag": "Literal: solo funciona con comida/cuerpo",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.totalmedios.com/nota/22999/tu-cuerpo-pide-pasta-de-madre-para-mama-lucchetti",
    "frase_es": "Tu cuerpo pide pasta",
    "frase_pt": "Seu corpo pede massa",
    "pais_pt": "Argentina"
  },
  {
    "id": "6",
    "frase": "Dejá que la vida te despeine",
    "marca": "Sedal",
    "agencia": "JWT Argentina / El Hotel",
    "pais": "Argentina",
    "ano": "2005",
    "tipo": "Publicidad",
    "tema": "Identidad; Riesgo y valentía",
    "funcion": "Empuja a actuar",
    "tono": "Cálido",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": true,
    "premio_el_ojo": "",
    "link": "https://www.latinspots.com/noticia/deja-que-la-vida-te-despeine/9108",
    "frase_es": "Dejá que la vida te despeine",
    "frase_pt": "Deixe a vida te despentear",
    "pais_pt": "Argentina"
  },
  {
    "id": "8",
    "frase": "Bienvenido a la república independiente de tu casa",
    "marca": "IKEA",
    "agencia": "*S,C,P,F...",
    "pais": "España",
    "ano": "2006",
    "tipo": "Publicidad",
    "tema": "Placer y vida cotidiana; Identidad",
    "funcion": "Tranquiliza o relativiza",
    "tono": "Cálido",
    "flag": "Depende de contexto",
    "motivo_flag": "Habla de la casa (IKEA)",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.marketingdirecto.com/especiales/premios-eficacia/campanas-mas-eficaces-publicidad-espanola",
    "frase_es": "Bienvenido a la república independiente de tu casa",
    "frase_pt": "Bem-vindo à república independente da sua casa",
    "pais_pt": "Espanha"
  },
  {
    "id": "9",
    "frase": "¿Te gusta conducir?",
    "marca": "BMW",
    "agencia": "*S,C,P,F...",
    "pais": "España",
    "ano": "1999",
    "tipo": "Publicidad",
    "tema": "Identidad; Placer y vida cotidiana",
    "funcion": "Desafía o cuestiona",
    "tono": "Irónico",
    "flag": "Depende de contexto",
    "motivo_flag": "Funciona como contrapregunta; depende de BMW/manejar",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.marketingdirecto.com/especiales/premios-eficacia/campanas-mas-eficaces-publicidad-espanola",
    "frase_es": "¿Te gusta conducir?",
    "frase_pt": "Você gosta de dirigir?",
    "pais_pt": "Espanha"
  },
  {
    "id": "13",
    "frase": "Mi estilo se escribe con Z",
    "marca": "El Palacio de Hierro",
    "agencia": "Terán\\TBWA",
    "pais": "México",
    "ano": "2025",
    "tipo": "Publicidad",
    "tema": "Identidad",
    "funcion": "Sentencia de oráculo",
    "tono": "Provocador",
    "flag": "Depende de contexto",
    "motivo_flag": "La 'Z' pierde sentido sin el contexto de la marca",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.merca20.com/el-palacio-de-hierro-presenta-su-nueva-imagen-te-sorprendera/",
    "frase_es": "Mi estilo se escribe con Z",
    "frase_pt": "Meu estilo se escreve com Z",
    "pais_pt": "México"
  },
  {
    "id": "14",
    "frase": "Ser grande no es cuestión de edad",
    "marca": "El Palacio de Hierro",
    "agencia": "Terán\\TBWA",
    "pais": "México",
    "ano": "2025",
    "tipo": "Publicidad",
    "tema": "Identidad; Tiempo y país",
    "funcion": "Tranquiliza o relativiza",
    "tono": "Cálido",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": true,
    "premio_el_ojo": "",
    "link": "https://www.merca20.com/el-palacio-de-hierro-presenta-su-nueva-imagen-te-sorprendera/",
    "frase_es": "Ser grande no es cuestión de edad",
    "frase_pt": "Ser grande não é questão de idade",
    "pais_pt": "México"
  },
  {
    "id": "17",
    "frase": "Tem coisas que só a Philco faz pra você [Hay cosas que solo Philco hace por vos]",
    "marca": "Philco",
    "agencia": "F/Nazca",
    "pais": "Brasil",
    "ano": "s/d",
    "tipo": "Publicidad",
    "tema": "Amor y vínculos",
    "funcion": "Tranquiliza o relativiza",
    "tono": "Cálido",
    "flag": "Depende de contexto",
    "motivo_flag": "Portugués + marca de electrodomésticos",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.ifd.com.br/publicidade-e-propaganda/50-slogans-mais-lembrados/",
    "frase_es": "Tem coisas que só a Philco faz pra você [Hay cosas que solo Philco hace por vos]",
    "frase_pt": "Tem coisas que só a Philco faz pra você",
    "pais_pt": "Brasil"
  },
  {
    "id": "19",
    "frase": "Não tem comparação [No tiene comparación]",
    "marca": "Brastemp",
    "agencia": "Talent",
    "pais": "Brasil",
    "ano": "s/d",
    "tipo": "Publicidad",
    "tema": "Identidad; Placer y vida cotidiana",
    "funcion": "Sí o no rotundo",
    "tono": "Cálido",
    "flag": "OK",
    "motivo_flag": "Portugués (traducción entre corchetes)",
    "comodin": true,
    "premio_el_ojo": "",
    "link": "https://www.ifd.com.br/publicidade-e-propaganda/50-slogans-mais-lembrados/",
    "frase_es": "Não tem comparação [No tiene comparación]",
    "frase_pt": "Não tem comparação",
    "pais_pt": "Brasil"
  },
  {
    "id": "21",
    "frase": "no creérsela, no ser hijo de puta, escuchar a los demás",
    "marca": "El Ojo – Charla",
    "agencia": "Equipo Wieden+Kennedy Latam",
    "pais": "Regional",
    "ano": "2025",
    "tipo": "El Ojo",
    "tema": "Trabajo y creatividad; Identidad",
    "funcion": "Empuja a actuar",
    "tono": "Provocador",
    "flag": "Revisar",
    "motivo_flag": "Lenguaje fuerte ('hijo de puta')",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.ifd.com.br/publicidade-e-propaganda/50-slogans-mais-lembrados/",
    "frase_es": "no creérsela, no ser hijo de puta, escuchar a los demás",
    "frase_pt": "não se achar, não ser filho da puta, escutar os outros",
    "pais_pt": "Regional"
  },
  {
    "id": "22",
    "frase": "…me gustaría ver más anuncios de cerveza, de bancos, de salchichas, porque ese es nuestro trabajo real",
    "marca": "El Ojo – Charla",
    "agencia": "Toni Segarra, Alegre Roca",
    "pais": "España",
    "ano": "2023",
    "tipo": "El Ojo",
    "tema": "Trabajo y creatividad",
    "funcion": "Desafía o cuestiona",
    "tono": "Provocador",
    "flag": "Depende de contexto",
    "motivo_flag": "Fragmento con '…'; habla de publicidad",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.elojodeiberoamerica.com/revivimos-los-mas-destacado-de-las-conferencias-de-el-ojo-2025/",
    "frase_es": "…me gustaría ver más anuncios de cerveza, de bancos, de salchichas, porque ese es nuestro trabajo real",
    "frase_pt": "…eu gostaria de ver mais anúncios de cerveja, de bancos, de salsichas, porque esse é o nosso trabalho de verdade",
    "pais_pt": "Espanha"
  },
  {
    "id": "23",
    "frase": "La publicidad no ha cambiado sino envejecido, hagámosla nuevamente sexy",
    "marca": "El Ojo – Charla",
    "agencia": "Per Pedersen, Global Creative Chairman de Grey",
    "pais": "Global",
    "ano": "2017",
    "tipo": "El Ojo",
    "tema": "Trabajo y creatividad; Tiempo y país",
    "funcion": "Desafía o cuestiona",
    "tono": "Irónico",
    "flag": "OK",
    "motivo_flag": "Habla de publicidad",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.latinspots.com/noticia/as-vivi-toni-segarra-su-ingreso-al-saln-de-honor-del-talento-latino/68216",
    "frase_es": "La publicidad no ha cambiado sino envejecido, hagámosla nuevamente sexy",
    "frase_pt": "A publicidade não mudou, e sim envelheceu, vamos torná-la sexy de novo",
    "pais_pt": "Global"
  },
  {
    "id": "24",
    "frase": "…caemos en la rutina y, más de una vez, pensamos en divorciarnos",
    "marca": "El Ojo – Charla",
    "agencia": "Marina Stern, Mercado McCann",
    "pais": "Argentina",
    "ano": "2021",
    "tipo": "El Ojo",
    "tema": "Amor y vínculos; Tiempo y país",
    "funcion": "Sentencia de oráculo",
    "tono": "Irónico",
    "flag": "Depende de contexto",
    "motivo_flag": "Fragmento con '…'",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.elojodeiberoamerica.com/review-ojo-2017-20-anos-pensamiento-creativo-iberoamerica/",
    "frase_es": "…caemos en la rutina y, más de una vez, pensamos en divorciarnos",
    "frase_pt": "…caímos na rotina e, mais de uma vez, pensamos em nos divorciar",
    "pais_pt": "Argentina"
  },
  {
    "id": "26",
    "frase": "la empatía es el mejor GPS",
    "marca": "El Ojo – Entrevista",
    "agencia": "Omar Carrión, Kellanova Latin America",
    "pais": "s/d",
    "ano": "2025 (?)",
    "tipo": "El Ojo",
    "tema": "Amor y vínculos; Trabajo y creatividad",
    "funcion": "Sentencia de oráculo",
    "tono": "Cálido",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": true,
    "premio_el_ojo": "",
    "link": "https://www.latinspots.com/noticia/el-ojo-de-iberoamrica-2021-cultura-emociones-e-inclusin/61138",
    "frase_es": "la empatía es el mejor GPS",
    "frase_pt": "a empatia é o melhor GPS",
    "pais_pt": "s/d"
  },
  {
    "id": "27",
    "frase": "Yo creo que sacamos petróleo debajo de una piedra.",
    "marca": "El Ojo – Entrevista",
    "agencia": "Antonio Montero López, Contrapunto",
    "pais": "España",
    "ano": "2004",
    "tipo": "El Ojo",
    "tema": "Trabajo y creatividad",
    "funcion": "Sí o no rotundo",
    "tono": "Irónico",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.latinspots.com/noticia/latinspots185-creatividad-para-un-mundo-incierto/91670",
    "frase_es": "Yo creo que sacamos petróleo debajo de una piedra.",
    "frase_pt": "Eu acho que tiramos petróleo de debaixo de uma pedra.",
    "pais_pt": "Espanha"
  },
  {
    "id": "28",
    "frase": "Las personas son más inteligentes de lo que las marcas piensan",
    "marca": "El Ojo – Charla",
    "agencia": "Lucía \"Pistola\" Mendoza, Twitter México & Latam",
    "pais": "México",
    "ano": "2021",
    "tipo": "El Ojo",
    "tema": "Trabajo y creatividad; Identidad",
    "funcion": "Desafía o cuestiona",
    "tono": "Provocador",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.latinspots.com/noticia/popai-argentina-invita-a-participar-del-taller-shopper-marketing/6491?section=negocios",
    "frase_es": "Las personas son más inteligentes de lo que las marcas piensan",
    "frase_pt": "As pessoas são mais inteligentes do que as marcas pensam",
    "pais_pt": "México"
  },
  {
    "id": "29",
    "frase": "Original es una trampa. Lo fresco es libertad",
    "marca": "El Ojo – Charla",
    "agencia": "Sergio Gordilho, Africa Creative",
    "pais": "Brasil",
    "ano": "2025",
    "tipo": "El Ojo",
    "tema": "Trabajo y creatividad; Identidad",
    "funcion": "Desafía o cuestiona",
    "tono": "Provocador",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.latinspots.com/noticia/el-ojo-de-iberoamrica-2021-cultura-emociones-e-inclusin/61138",
    "frase_es": "Original es una trampa. Lo fresco es libertad",
    "frase_pt": "Original é uma armadilha. O fresco é liberdade",
    "pais_pt": "Brasil"
  },
  {
    "id": "30",
    "frase": "El AI concluye. La creatividad humana desordena, es curiosa, explora.",
    "marca": "El Ojo – Charla",
    "agencia": "Damasia Merbilháa, TBWA\\Worldwide",
    "pais": "Argentina",
    "ano": "2025",
    "tipo": "El Ojo",
    "tema": "Futuro y tecnología",
    "funcion": "Sentencia de oráculo",
    "tono": "Profético",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.elojodeiberoamerica.com/revivimos-los-mas-destacado-de-las-conferencias-de-el-ojo-2025/",
    "frase_es": "El AI concluye. La creatividad humana desordena, es curiosa, explora.",
    "frase_pt": "A IA conclui. A criatividade humana bagunça, é curiosa, explora.",
    "pais_pt": "Argentina"
  },
  {
    "id": "31",
    "frase": "La única forma de innovar, es no pretenderlo.",
    "marca": "El Ojo – Charla",
    "agencia": "Álex de la Iglesia, director y guionista",
    "pais": "España",
    "ano": "2018",
    "tipo": "El Ojo",
    "tema": "Futuro y tecnología; Trabajo y creatividad",
    "funcion": "Sentencia de oráculo",
    "tono": "Profético",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.elojodeiberoamerica.com/revivimos-los-mas-destacado-de-las-conferencias-de-el-ojo-2025/",
    "frase_es": "La única forma de innovar, es no pretenderlo.",
    "frase_pt": "A única forma de inovar é não ter essa pretensão.",
    "pais_pt": "Espanha"
  },
  {
    "id": "32",
    "frase": "la valentía es contagiosa",
    "marca": "El Ojo – Charla",
    "agencia": "Equipo LePub Mexico City + Tecate",
    "pais": "México",
    "ano": "2025",
    "tipo": "El Ojo",
    "tema": "Riesgo y valentía",
    "funcion": "Empuja a actuar",
    "tono": "Cálido",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": true,
    "premio_el_ojo": "",
    "link": "https://www.infobae.com/espacio-no-editorial/2018/11/06/la-celebracion-de-la-creatividad-regional-todos-los-ganadores-de-el-ojo-de-iberoamerica/",
    "frase_es": "la valentía es contagiosa",
    "frase_pt": "a coragem é contagiosa",
    "pais_pt": "México"
  },
  {
    "id": "34",
    "frase": "el algoritmo es nuestro caballo de Troya para hacer una revolución",
    "marca": "El Ojo – Charla",
    "agencia": "Alejandro Di Trolio, Cheil Worldwide",
    "pais": "España (?)",
    "ano": "2025",
    "tipo": "El Ojo",
    "tema": "Futuro y tecnología; Riesgo y valentía",
    "funcion": "Empuja a actuar",
    "tono": "Provocador",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.elojodeiberoamerica.com/revivimos-los-mas-destacado-de-las-conferencias-de-el-ojo-2025/",
    "frase_es": "el algoritmo es nuestro caballo de Troya para hacer una revolución",
    "frase_pt": "o algoritmo é o nosso cavalo de Troia para fazer uma revolução",
    "pais_pt": "España (?)"
  },
  {
    "id": "35",
    "frase": "la idea siempre está primero",
    "marca": "El Ojo – Charla",
    "agencia": "Rafa Quijano y Daro González, VML Argentina",
    "pais": "Argentina",
    "ano": "2025",
    "tipo": "El Ojo",
    "tema": "Trabajo y creatividad",
    "funcion": "Sentencia de oráculo",
    "tono": "Profético",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.elojodeiberoamerica.com/revivimos-los-mas-destacado-de-las-conferencias-de-el-ojo-2025/",
    "frase_es": "la idea siempre está primero",
    "frase_pt": "a ideia sempre vem primeiro",
    "pais_pt": "Argentina"
  },
  {
    "id": "37",
    "frase": "ser creativo hoy no es solo hacer cosas lindas, es tomar posición",
    "marca": "El Ojo – Charla",
    "agencia": "Kike Renta, DDB Latina Puerto Rico",
    "pais": "Puerto Rico",
    "ano": "2025",
    "tipo": "El Ojo",
    "tema": "Trabajo y creatividad; Identidad",
    "funcion": "Empuja a actuar",
    "tono": "Provocador",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.elojodeiberoamerica.com/revivimos-los-mas-destacado-de-las-conferencias-de-el-ojo-2025/",
    "frase_es": "ser creativo hoy no es solo hacer cosas lindas, es tomar posición",
    "frase_pt": "ser criativo hoje não é só fazer coisas bonitas, é tomar posição",
    "pais_pt": "Porto Rico"
  },
  {
    "id": "39",
    "frase": "La creatividad es el antídoto",
    "marca": "El Ojo – Entrevista",
    "agencia": "Tomás Ostiglia, LOLA MullenLowe",
    "pais": "España",
    "ano": "2025",
    "tipo": "El Ojo",
    "tema": "Futuro y tecnología; Trabajo y creatividad",
    "funcion": "Tranquiliza o relativiza",
    "tono": "Profético",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": true,
    "premio_el_ojo": "",
    "link": "https://www.latinspots.com/noticia/el-ojo-de-iberoamrica-2025-ia-creatividad-humana-y-nuevas-fronteras/95096",
    "frase_es": "La creatividad es el antídoto",
    "frase_pt": "A criatividade é o antídoto",
    "pais_pt": "Espanha"
  },
  {
    "id": "40",
    "frase": "Lo más importante de las ideas es hacerlas",
    "marca": "El Ojo – Entrevista",
    "agencia": "Tomás Ostiglia, LOLA MullenLowe",
    "pais": "España",
    "ano": "2018",
    "tipo": "El Ojo",
    "tema": "Trabajo y creatividad; Riesgo y valentía",
    "funcion": "Empuja a actuar",
    "tono": "Directo",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": true,
    "premio_el_ojo": "",
    "link": "https://www.latinspots.com/noticia/latinspots185-creatividad-para-un-mundo-incierto/91670",
    "frase_es": "Lo más importante de las ideas es hacerlas",
    "frase_pt": "O mais importante das ideias é fazê-las",
    "pais_pt": "Espanha"
  },
  {
    "id": "41",
    "frase": "Cuando tienes data, puedes vender creatividad más arriesgada con menos riesgo",
    "marca": "El Ojo – Charla",
    "agencia": "Ciro Sarmiento, Dieste",
    "pais": "EE.UU.",
    "ano": "2017",
    "tipo": "El Ojo",
    "tema": "Futuro y tecnología; Riesgo y valentía; Trabajo y creatividad",
    "funcion": "Sentencia de oráculo",
    "tono": "Directo",
    "flag": "Depende de contexto",
    "motivo_flag": "Jerga de data/ventas",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.latinspots.com/sp/noticia/ranking-las-ideas-ms-premiadas-de-el-ojo-2018/49257",
    "frase_es": "Cuando tienes data, puedes vender creatividad más arriesgada con menos riesgo",
    "frase_pt": "Quando você tem dados, pode vender criatividade mais arriscada com menos risco",
    "pais_pt": "EUA"
  },
  {
    "id": "44",
    "frase": "el talento camina en todas direcciones",
    "marca": "El Ojo – Entrevista",
    "agencia": "Antonio Montero López, Contrapunto",
    "pais": "España",
    "ano": "2004",
    "tipo": "El Ojo",
    "tema": "Trabajo y creatividad; Identidad",
    "funcion": "Tranquiliza o relativiza",
    "tono": "Cálido",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.elojodeiberoamerica.com/review-ojo-2017-20-anos-pensamiento-creativo-iberoamerica/",
    "frase_es": "el talento camina en todas direcciones",
    "frase_pt": "o talento caminha em todas as direções",
    "pais_pt": "Espanha"
  },
  {
    "id": "45",
    "frase": "las ideas deben ser más grandes que avisos",
    "marca": "El Ojo – Entrevista",
    "agencia": "Pablo del Campo",
    "pais": "Argentina",
    "ano": "2024",
    "tipo": "El Ojo",
    "tema": "Trabajo y creatividad; Riesgo y valentía",
    "funcion": "Empuja a actuar",
    "tono": "Provocador",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.latinspots.com/noticia/popai-argentina-invita-a-participar-del-taller-shopper-marketing/6491?section=negocios",
    "frase_es": "las ideas deben ser más grandes que avisos",
    "frase_pt": "as ideias devem ser maiores que anúncios",
    "pais_pt": "Argentina"
  },
  {
    "id": "48",
    "frase": "Es la primera idea con la que realmente sentimos que había peligro a la hora de hacerla…",
    "marca": "El Ojo – Entrevista",
    "agencia": "Pancho Cassis, LOLA MullenLowe",
    "pais": "España",
    "ano": "2018",
    "tipo": "El Ojo",
    "tema": "Riesgo y valentía",
    "funcion": "Sentencia de oráculo",
    "tono": "Profético",
    "flag": "Depende de contexto",
    "motivo_flag": "Fragmento con '…'",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.elojodeiberoamerica.com/pablo-del-campo-ingresa-en-el-salon-de-honor-del-talento-latino/",
    "frase_es": "Es la primera idea con la que realmente sentimos que había peligro a la hora de hacerla…",
    "frase_pt": "É a primeira ideia com a qual realmente sentimos que havia perigo na hora de fazê-la…",
    "pais_pt": "Espanha"
  },
  {
    "id": "53",
    "frase": "Tenemos que vernos más",
    "marca": "Ruavieja",
    "agencia": "Leo Burnett España",
    "pais": "España",
    "ano": "2017",
    "tipo": "Publicidad",
    "tema": "Amor y vínculos",
    "funcion": "Empuja a actuar",
    "tono": "Cálido",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.marketingdirecto.com/imprescindibles/historia-marcas/historia-campofrio-anuncios-navidad",
    "frase_es": "Tenemos que vernos más",
    "frase_pt": "Temos que nos ver mais",
    "pais_pt": "Espanha"
  },
  {
    "id": "55",
    "frase": "Tomou? [¿Tomaste?]",
    "marca": "Parmalat",
    "agencia": "DM9",
    "pais": "Brasil",
    "ano": "1996",
    "tipo": "Publicidad",
    "tema": "Placer y vida cotidiana",
    "funcion": "Desafía o cuestiona",
    "tono": "Absurdo",
    "flag": "Depende de contexto",
    "motivo_flag": "Portugués + leche; solo funciona con comida/bebida",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.latinspots.com/noticia/leo-burnett-espaa-propone-volver-a-las-amistades-autnticas-con-licores-ruavieja/45730",
    "frase_es": "Tomou? [¿Tomaste?]",
    "frase_pt": "Tomou?",
    "pais_pt": "Brasil"
  },
  {
    "id": "57",
    "frase": "En navidad todo es posible.",
    "marca": "Ministerio de Defensa de Colombia",
    "agencia": "Lowe-SSP3",
    "pais": "Colombia",
    "ano": "2010",
    "tipo": "Publicidad",
    "tema": "Futuro y tecnología; Tiempo y país",
    "funcion": "Sí o no rotundo",
    "tono": "Cálido",
    "flag": "Depende de contexto",
    "motivo_flag": "Estacional (Navidad)",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://exame.com/marketing/parmalat-e-os-mamiferos-que-marcaram-o-brasil/",
    "frase_es": "En navidad todo es posible.",
    "frase_pt": "No Natal tudo é possível.",
    "pais_pt": "Colômbia"
  },
  {
    "id": "60",
    "frase": "¿Es muy tonto lo que estoy diciendo?",
    "marca": "VTR",
    "agencia": "Porta",
    "pais": "Chile",
    "ano": "2012",
    "tipo": "Publicidad",
    "tema": "Amor y vínculos; Identidad",
    "funcion": "Desafía o cuestiona",
    "tono": "Irónico",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.semana.com/pais/articulo/colombia-mercadeo-navidad-para-ganar-guerra/141091/",
    "frase_es": "¿Es muy tonto lo que estoy diciendo?",
    "frase_pt": "É muito bobo o que estou dizendo?",
    "pais_pt": "Chile"
  },
  {
    "id": "63",
    "frase": "Huevo estrellado",
    "marca": "Bachoco",
    "agencia": "Terán\\TBWA",
    "pais": "México",
    "ano": "",
    "tipo": "Publicidad",
    "tema": "Placer y vida cotidiana",
    "funcion": "Humor o absurdo",
    "tono": "Absurdo",
    "flag": "Depende de contexto",
    "motivo_flag": "Literal: nombre de producto",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.produ.com/mercadeo/noticias/leo-burnett-mexico-y-corona-senalan-que-america-siempre-ha-sido-grande-en-un-nuevo-spot/",
    "frase_es": "Huevo estrellado",
    "frase_pt": "Ovo estrelado",
    "pais_pt": "México"
  },
  {
    "id": "66",
    "frase": "Canelón de Pollo",
    "marca": "Bachoco",
    "agencia": "Terán\\TBWA (?)",
    "pais": "México",
    "ano": "",
    "tipo": "Publicidad",
    "tema": "Placer y vida cotidiana",
    "funcion": "Humor o absurdo",
    "tono": "Absurdo",
    "flag": "Depende de contexto",
    "motivo_flag": "Literal: nombre de producto",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.elfinanciero.com.mx/food-and-drink/2025/09/21/hoy-toca-pollo-quien-es-dueno-de-bachoco-marca-que-innovo-con-la-venta-de-huevos-por-docena/",
    "frase_es": "Canelón de Pollo",
    "frase_pt": "Canelone de Frango",
    "pais_pt": "México"
  },
  {
    "id": "68",
    "frase": "Todos somos expertos",
    "marca": "Banca de Quinielas del Uruguay",
    "agencia": "Publicis Ímpetu",
    "pais": "Uruguay",
    "ano": "2019",
    "tipo": "Publicidad",
    "tema": "Identidad; Trabajo y creatividad",
    "funcion": "Tranquiliza o relativiza",
    "tono": "Cálido",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": true,
    "premio_el_ojo": "",
    "link": "https://naranti.com/noticias/anuncios-espectaculares-bachoco",
    "frase_es": "Todos somos expertos",
    "frase_pt": "Todos somos especialistas",
    "pais_pt": "Uruguai"
  },
  {
    "id": "69",
    "frase": "Seguí moviéndote",
    "marca": "Ford",
    "agencia": "JWT Argentina",
    "pais": "Argentina",
    "ano": "",
    "tipo": "Publicidad",
    "tema": "Riesgo y valentía; Futuro y tecnología",
    "funcion": "Empuja a actuar",
    "tono": "Directo",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": true,
    "premio_el_ojo": "",
    "link": "https://www.adlatina.com/publicidad/publicis-%C3%ADmpetu-y-banca-de-quinielas-de-uruguay-se-consagraron-con-el-gran-effie",
    "frase_es": "Seguí moviéndote",
    "frase_pt": "Continue se movendo",
    "pais_pt": "Argentina"
  },
  {
    "id": "70",
    "frase": "Para abrir caminos se necesita maquinaria pesada",
    "marca": "Holcim Ecuador",
    "agencia": "Maruri Grey",
    "pais": "Ecuador",
    "ano": "2023",
    "tipo": "Publicidad",
    "tema": "Riesgo y valentía; Trabajo y creatividad",
    "funcion": "Sentencia de oráculo",
    "tono": "Directo",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.lanacion.com.ar/economia/la-publicidad-debe-ser-amigable-y-respetuosa-del-consumidor-nid1423265/",
    "frase_es": "Para abrir caminos se necesita maquinaria pesada",
    "frase_pt": "Para abrir caminhos é preciso maquinário pesado",
    "pais_pt": "Equador"
  },
  {
    "id": "72",
    "frase": "Naturalmente impredecible",
    "marca": "Del Sur",
    "agencia": "Paradais DDB",
    "pais": "Ecuador",
    "ano": "2023",
    "tipo": "Publicidad",
    "tema": "Futuro y tecnología; Identidad",
    "funcion": "Sentencia de oráculo",
    "tono": "Profético",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": true,
    "premio_el_ojo": "",
    "link": "https://www.eluniverso.com/larevista/sociedad/effie-awards-ecuador-cumplio-dos-decadas-de-premiar-a-las-ideas-que-funcionan-nota/",
    "frase_es": "Naturalmente impredecible",
    "frase_pt": "Naturalmente imprevisível",
    "pais_pt": "Equador"
  },
  {
    "id": "74",
    "frase": "Eran otros tiempos",
    "marca": "Quilmes",
    "agencia": "Young & Rubicam",
    "pais": "Argentina",
    "ano": "2002",
    "tipo": "Publicidad",
    "tema": "Tiempo y país",
    "funcion": "Tranquiliza o relativiza",
    "tono": "Irónico",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.adlatina.com/publicidad/%E2%80%9Chimno%E2%80%9D-un-homenaje-al-f%C3%BAtbol",
    "frase_es": "Eran otros tiempos",
    "frase_pt": "Eram outros tempos",
    "pais_pt": "Argentina"
  },
  {
    "id": "75",
    "frase": "Lo importante es el chip",
    "marca": "CTI",
    "agencia": "",
    "pais": "Argentina",
    "ano": "2004",
    "tipo": "Publicidad",
    "tema": "Futuro y tecnología",
    "funcion": "Sentencia de oráculo",
    "tono": "Directo",
    "flag": "Depende de contexto",
    "motivo_flag": "Habla de un chip/celular (CTI)",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.youtube.com/watch?v=VWkkWe8U_n8",
    "frase_es": "Lo importante es el chip",
    "frase_pt": "O importante é o chip",
    "pais_pt": "Argentina"
  },
  {
    "id": "76",
    "frase": "Uno de cada 10 hombres es gay",
    "marca": "Fernet Cinzano",
    "agencia": "",
    "pais": "Argentina",
    "ano": "2004",
    "tipo": "Publicidad",
    "tema": "Identidad; Amor y vínculos",
    "funcion": "Humor o absurdo",
    "tono": "Provocador",
    "flag": "Revisar",
    "motivo_flag": "Tema sensible; evaluar si va en un oráculo público",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.youtube.com/watch?v=Sz48pFGybzc",
    "frase_es": "Uno de cada 10 hombres es gay",
    "frase_pt": "Um em cada 10 homens é gay",
    "pais_pt": "Argentina"
  },
  {
    "id": "77",
    "frase": "Hacele caso a tu sed",
    "marca": "Sprite",
    "agencia": "",
    "pais": "Argentina",
    "ano": "1998",
    "tipo": "Publicidad",
    "tema": "Placer y vida cotidiana; Identidad",
    "funcion": "Empuja a actuar",
    "tono": "Cálido",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": false,
    "premio_el_ojo": "",
    "link": "https://www.youtube.com/watch?v=iFQFw6vAxtA",
    "frase_es": "Hacele caso a tu sed",
    "frase_pt": "Obedeça a sua sede",
    "pais_pt": "Argentina"
  },
  {
    "id": "78",
    "frase": "Si no es para vos, no es para vos",
    "marca": "BAFICI",
    "agencia": "La Comunidad",
    "pais": "Argentina",
    "ano": "",
    "tipo": "Publicidad",
    "tema": "Identidad; Amor y vínculos",
    "funcion": "Tranquiliza o relativiza",
    "tono": "Directo",
    "flag": "OK",
    "motivo_flag": "",
    "comodin": true,
    "premio_el_ojo": "",
    "link": "https://www.adlatina.com/publicidad/preestreno-de-la-comunidad-para-el-bafici",
    "frase_es": "Si no es para vos, no es para vos",
    "frase_pt": "Se não é pra você, não é pra você",
    "pais_pt": "Argentina"
  },
  {
    "id": "79",
    "frase": "No es para ti",
    "marca": "Ford F-150",
    "agencia": "JWT San Juan",
    "pais": "Puerto Rico",
    "ano": "2009",
    "tipo": "Publicidad",
    "tema": "Identidad; Riesgo y valentía",
    "funcion": "Sí o no rotundo",
    "tono": "Provocador",
    "flag": "OK",
    "motivo_flag": "Nombre de la pieza premiada; confirmar que funciona como frase al aire",
    "comodin": true,
    "premio_el_ojo": "Plata – El Ojo Innovador, Radio",
    "link": "https://www.adlatina.com/articulo.php?slug=%2Fpublicidad%2Ftodos-los-ganadores-del-ojo-de-iberoam%C3%A9rica",
    "frase_es": "No es para ti",
    "frase_pt": "Não é para você",
    "pais_pt": "Porto Rico"
  },
  {
    "id": "82",
    "frase": "Devolvele la guita al taxista",
    "marca": "Publicis Graffiti (institucional)",
    "agencia": "Publicis Graffiti Argentina",
    "pais": "Argentina",
    "ano": "2009",
    "tipo": "Publicidad",
    "tema": "Identidad; Riesgo y valentía",
    "funcion": "Empuja a actuar",
    "tono": "Irónico",
    "flag": "OK",
    "motivo_flag": "Nombre de la pieza premiada; confirmar que funciona como frase al aire; argentinismo (guita)",
    "comodin": true,
    "premio_el_ojo": "Bronce – El Ojo Promo, Activación",
    "link": "https://www.adlatina.com/articulo.php?slug=%2Fpublicidad%2Ftodos-los-ganadores-del-ojo-de-iberoam%C3%A9rica",
    "frase_es": "Devolvele la guita al taxista",
    "frase_pt": "Devolve a grana pro taxista",
    "pais_pt": "Argentina"
  },
  {
    "id": "83",
    "frase": "Que vuelvan los lentos",
    "marca": "Doritos",
    "agencia": "BBDO Argentina",
    "pais": "Argentina",
    "ano": "2009",
    "tipo": "Publicidad",
    "tema": "Amor y vínculos; Tiempo y país",
    "funcion": "Sentencia de oráculo",
    "tono": "Irónico",
    "flag": "OK",
    "motivo_flag": "Nombre de la pieza premiada; confirmar que funciona como frase al aire",
    "comodin": false,
    "premio_el_ojo": "Oro – El Ojo Campañas Integradas (Productos)",
    "link": "https://www.adlatina.com/articulo.php?slug=%2Fpublicidad%2Ftodos-los-ganadores-del-ojo-de-iberoam%C3%A9rica",
    "frase_es": "Que vuelvan los lentos",
    "frase_pt": "Que voltem as lentas",
    "pais_pt": "Argentina"
  },
  {
    "id": "86",
    "frase": "Con poco me lo monto",
    "marca": "Fanta",
    "agencia": "McCann Erickson España",
    "pais": "España",
    "ano": "2009",
    "tipo": "Publicidad",
    "tema": "Trabajo y creatividad; Placer y vida cotidiana",
    "funcion": "Tranquiliza o relativiza",
    "tono": "Irónico",
    "flag": "OK",
    "motivo_flag": "Nombre de la pieza premiada; confirmar que funciona como frase al aire; expresión española",
    "comodin": false,
    "premio_el_ojo": "Bronce – El Ojo Promo (Promociones integradas)",
    "link": "https://www.adlatina.com/articulo.php?slug=%2Fpublicidad%2Ftodos-los-ganadores-del-ojo-de-iberoam%C3%A9rica",
    "frase_es": "Con poco me lo monto",
    "frase_pt": "Com pouco eu me viro",
    "pais_pt": "Espanha"
  }
]
};

// Alias de compatibilidad
CONFIG.TEST_PHRASES = CONFIG.CATALOG_PHRASES;

// Compatible con Node / ES Modules / Browser
if (typeof module !== 'undefined' && module.exports) {
  module.exports = CONFIG;
}
